version: "3.9"

services:
  streamlit:
    build:
      context: ./streamlit
      dockerfile: Dockerfile
    container_name: 'streamlit'
    # M1 macの場合
    #platform: linux/x86_64
    restart: always
    tty: true
    expose:
      - "8060"
    ports:
      - "8060:8060"
    working_dir: '/root/'
    volumes:
      - /Users/tanakatouma/vscode/streamlit-docker/streamlit/src/:/root/src/
#      - /Users/tanakatouma/Documents/Docker_volumes/ds_mlops/dash:/root/dash/

     

